name: email-changed-folders
on: push
#on: workflow_dispatch
jobs:
  email-notification-for-changed-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Get Changed Directory
        uses: Stockopedia/action-get-changed-files@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: false 
          format: csv

      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }}
