name: Folder Listener
#on: push
on:
  push:
    branches:
      - main         #to be changed to master

jobs:
  folder-listener:
    runs-on: ubuntu-latest
    env:
        LISTENING_FOLDER : api/app/controllers
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      - name: Get changed files in ${{ env. LISTENING_FOLDER }}
        id: changed-files-specific
        uses: tj-actions/changed-files@v37
        with:
            #separator: ","
            files: ${{ env. LISTENING_FOLDER }}
 
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files in ${{ env. LISTENING_FOLDER }}
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          file_changed_html=''
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
            file_changed_html+="${file}<br />"
          done
          echo "FILES_CHANGED_HTML=$file_changed_html" >> $GITHUB_ENV

      - name: Send email
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: ALV API Controllers-GitHub Updated
          # Required recipients' addresses:
          to: vijaik.nd@gmail.com #, vishali.nagathevan@gmail.com, kumvijaya@gmail.com
          # Required sender full name (address can be skipped):
          from:  ALVDIGITAL Systems (API)
          # Optional plain body:
          html_body: |
            <b>List of files changed in ${{ env.LISTENING_FOLDER }}</b>
            <hr>
            <pre>
            ${{ steps.changed-files-specific.outputs.all_changed_files }}
            
            </pre>
            <b>Commit Comment</b>
            <hr>
            <pre>
            ${{ github.event.head_commit.message }}


            <b>This is an automated email. If you have questions about the above, please email to service@alvdigital.com</b>
            </pre>

          #body: echo $changedfiles
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: vijaik.nd@gmail.com, vishali.nagathevan@gmail.com
          # Optional blind carbon copy recipients:
          bcc: vijaik.nd@gmail.com, vishali.nagathevan@gmail.com
          # Optional recipient of the email response:
          #reply_to: vijaik.nd@gmail.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <vijaik.nd@gmail.com>
          # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # attachments: test.txt
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
    